//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("OBLIVIUS_MAINModel", "FK_User_Party", "VE_Parties", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MVC_TestBed.Models.VE_Parties), "VE_Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVC_TestBed.Models.VE_Users), true)]

#endregion

namespace MVC_TestBed.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VE_Parties> VE_Parties
        {
            get
            {
                if ((_VE_Parties == null))
                {
                    _VE_Parties = base.CreateObjectSet<VE_Parties>("VE_Parties");
                }
                return _VE_Parties;
            }
        }
        private ObjectSet<VE_Parties> _VE_Parties;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VE_Users> VE_Users
        {
            get
            {
                if ((_VE_Users == null))
                {
                    _VE_Users = base.CreateObjectSet<VE_Users>("VE_Users");
                }
                return _VE_Users;
            }
        }
        private ObjectSet<VE_Users> _VE_Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VE_Parties EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVE_Parties(VE_Parties vE_Parties)
        {
            base.AddObject("VE_Parties", vE_Parties);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VE_Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVE_Users(VE_Users vE_Users)
        {
            base.AddObject("VE_Users", vE_Users);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="weightByAgeGroup">No Metadata Documentation available.</param>
        /// <param name="weightByPerif">No Metadata Documentation available.</param>
        /// <param name="filter18">No Metadata Documentation available.</param>
        /// <param name="filterIP">No Metadata Documentation available.</param>
        public ObjectResult<GetResults_Result> GetResults(Nullable<global::System.Boolean> weightByAgeGroup, Nullable<global::System.Boolean> weightByPerif, Nullable<global::System.Boolean> filter18, Nullable<global::System.Boolean> filterIP)
        {
            ObjectParameter weightByAgeGroupParameter;
            if (weightByAgeGroup.HasValue)
            {
                weightByAgeGroupParameter = new ObjectParameter("WeightByAgeGroup", weightByAgeGroup);
            }
            else
            {
                weightByAgeGroupParameter = new ObjectParameter("WeightByAgeGroup", typeof(global::System.Boolean));
            }
    
            ObjectParameter weightByPerifParameter;
            if (weightByPerif.HasValue)
            {
                weightByPerifParameter = new ObjectParameter("WeightByPerif", weightByPerif);
            }
            else
            {
                weightByPerifParameter = new ObjectParameter("WeightByPerif", typeof(global::System.Boolean));
            }
    
            ObjectParameter filter18Parameter;
            if (filter18.HasValue)
            {
                filter18Parameter = new ObjectParameter("Filter18", filter18);
            }
            else
            {
                filter18Parameter = new ObjectParameter("Filter18", typeof(global::System.Boolean));
            }
    
            ObjectParameter filterIPParameter;
            if (filterIP.HasValue)
            {
                filterIPParameter = new ObjectParameter("FilterIP", filterIP);
            }
            else
            {
                filterIPParameter = new ObjectParameter("FilterIP", typeof(global::System.Boolean));
            }
    
            return base.ExecuteFunction<GetResults_Result>("GetResults", weightByAgeGroupParameter, weightByPerifParameter, filter18Parameter, filterIPParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="partyId">No Metadata Documentation available.</param>
        public ObjectResult<PartyByAge_Result> PartyByAge(Nullable<global::System.Int32> partyId)
        {
            ObjectParameter partyIdParameter;
            if (partyId.HasValue)
            {
                partyIdParameter = new ObjectParameter("partyId", partyId);
            }
            else
            {
                partyIdParameter = new ObjectParameter("partyId", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<PartyByAge_Result>("PartyByAge", partyIdParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="partyId">No Metadata Documentation available.</param>
        public ObjectResult<PartyByPerif_Result> PartyByPerif(Nullable<global::System.Int32> partyId)
        {
            ObjectParameter partyIdParameter;
            if (partyId.HasValue)
            {
                partyIdParameter = new ObjectParameter("partyId", partyId);
            }
            else
            {
                partyIdParameter = new ObjectParameter("partyId", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<PartyByPerif_Result>("PartyByPerif", partyIdParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OBLIVIUS_MAINModel", Name="VE_Parties")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VE_Parties : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VE_Parties object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static VE_Parties CreateVE_Parties(global::System.Int32 id, global::System.String name)
        {
            VE_Parties vE_Parties = new VE_Parties();
            vE_Parties.ID = id;
            vE_Parties.Name = name;
            return vE_Parties;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Elections2012
        {
            get
            {
                return _Elections2012;
            }
            set
            {
                OnElections2012Changing(value);
                ReportPropertyChanging("Elections2012");
                _Elections2012 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Elections2012");
                OnElections2012Changed();
            }
        }
        private Nullable<global::System.Decimal> _Elections2012;
        partial void OnElections2012Changing(Nullable<global::System.Decimal> value);
        partial void OnElections2012Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> InEuro2014
        {
            get
            {
                return _InEuro2014;
            }
            set
            {
                OnInEuro2014Changing(value);
                ReportPropertyChanging("InEuro2014");
                _InEuro2014 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InEuro2014");
                OnInEuro2014Changed();
            }
        }
        private Nullable<global::System.Boolean> _InEuro2014;
        partial void OnInEuro2014Changing(Nullable<global::System.Boolean> value);
        partial void OnInEuro2014Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> iFactor
        {
            get
            {
                return _iFactor;
            }
            set
            {
                OniFactorChanging(value);
                ReportPropertyChanging("iFactor");
                _iFactor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iFactor");
                OniFactorChanged();
            }
        }
        private Nullable<global::System.Double> _iFactor;
        partial void OniFactorChanging(Nullable<global::System.Double> value);
        partial void OniFactorChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OBLIVIUS_MAINModel", "FK_User_Party", "VE_Users")]
        public EntityCollection<VE_Users> VE_Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VE_Users>("OBLIVIUS_MAINModel.FK_User_Party", "VE_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VE_Users>("OBLIVIUS_MAINModel.FK_User_Party", "VE_Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OBLIVIUS_MAINModel", Name="VE_Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VE_Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VE_Users object.
        /// </summary>
        /// <param name="mAC">Initial value of the MAC property.</param>
        /// <param name="ageID">Initial value of the AgeID property.</param>
        /// <param name="perifID">Initial value of the PerifID property.</param>
        /// <param name="genderID">Initial value of the GenderID property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static VE_Users CreateVE_Users(global::System.String mAC, global::System.Int32 ageID, global::System.Int32 perifID, global::System.Int32 genderID, global::System.Int32 id)
        {
            VE_Users vE_Users = new VE_Users();
            vE_Users.MAC = mAC;
            vE_Users.AgeID = ageID;
            vE_Users.PerifID = perifID;
            vE_Users.GenderID = genderID;
            vE_Users.ID = id;
            return vE_Users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MAC
        {
            get
            {
                return _MAC;
            }
            set
            {
                if (_MAC != value)
                {
                    OnMACChanging(value);
                    ReportPropertyChanging("MAC");
                    _MAC = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MAC");
                    OnMACChanged();
                }
            }
        }
        private global::System.String _MAC;
        partial void OnMACChanging(global::System.String value);
        partial void OnMACChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AgeID
        {
            get
            {
                return _AgeID;
            }
            set
            {
                OnAgeIDChanging(value);
                ReportPropertyChanging("AgeID");
                _AgeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AgeID");
                OnAgeIDChanged();
            }
        }
        private global::System.Int32 _AgeID;
        partial void OnAgeIDChanging(global::System.Int32 value);
        partial void OnAgeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PerifID
        {
            get
            {
                return _PerifID;
            }
            set
            {
                OnPerifIDChanging(value);
                ReportPropertyChanging("PerifID");
                _PerifID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PerifID");
                OnPerifIDChanged();
            }
        }
        private global::System.Int32 _PerifID;
        partial void OnPerifIDChanging(global::System.Int32 value);
        partial void OnPerifIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GenderID
        {
            get
            {
                return _GenderID;
            }
            set
            {
                OnGenderIDChanging(value);
                ReportPropertyChanging("GenderID");
                _GenderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GenderID");
                OnGenderIDChanged();
            }
        }
        private global::System.Int32 _GenderID;
        partial void OnGenderIDChanging(global::System.Int32 value);
        partial void OnGenderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> When
        {
            get
            {
                return _When;
            }
            set
            {
                OnWhenChanging(value);
                ReportPropertyChanging("When");
                _When = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("When");
                OnWhenChanged();
            }
        }
        private Nullable<global::System.DateTime> _When;
        partial void OnWhenChanging(Nullable<global::System.DateTime> value);
        partial void OnWhenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PartyID
        {
            get
            {
                return _PartyID;
            }
            set
            {
                OnPartyIDChanging(value);
                ReportPropertyChanging("PartyID");
                _PartyID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartyID");
                OnPartyIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PartyID;
        partial void OnPartyIDChanging(Nullable<global::System.Int32> value);
        partial void OnPartyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> bad_mac
        {
            get
            {
                return _bad_mac;
            }
            set
            {
                Onbad_macChanging(value);
                ReportPropertyChanging("bad_mac");
                _bad_mac = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bad_mac");
                Onbad_macChanged();
            }
        }
        private Nullable<global::System.Byte> _bad_mac;
        partial void Onbad_macChanging(Nullable<global::System.Byte> value);
        partial void Onbad_macChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PrevElectionsPartyID
        {
            get
            {
                return _PrevElectionsPartyID;
            }
            set
            {
                OnPrevElectionsPartyIDChanging(value);
                ReportPropertyChanging("PrevElectionsPartyID");
                _PrevElectionsPartyID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrevElectionsPartyID");
                OnPrevElectionsPartyIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PrevElectionsPartyID;
        partial void OnPrevElectionsPartyIDChanging(Nullable<global::System.Int32> value);
        partial void OnPrevElectionsPartyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IPExists
        {
            get
            {
                return _IPExists;
            }
            set
            {
                OnIPExistsChanging(value);
                ReportPropertyChanging("IPExists");
                _IPExists = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IPExists");
                OnIPExistsChanged();
            }
        }
        private Nullable<global::System.Boolean> _IPExists;
        partial void OnIPExistsChanging(Nullable<global::System.Boolean> value);
        partial void OnIPExistsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreated;
        partial void OnDateCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PartyIdHidden
        {
            get
            {
                return _PartyIdHidden;
            }
            set
            {
                OnPartyIdHiddenChanging(value);
                ReportPropertyChanging("PartyIdHidden");
                _PartyIdHidden = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartyIdHidden");
                OnPartyIdHiddenChanged();
            }
        }
        private Nullable<global::System.Int32> _PartyIdHidden;
        partial void OnPartyIdHiddenChanging(Nullable<global::System.Int32> value);
        partial void OnPartyIdHiddenChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OBLIVIUS_MAINModel", "FK_User_Party", "VE_Parties")]
        public VE_Parties VE_Parties
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VE_Parties>("OBLIVIUS_MAINModel.FK_User_Party", "VE_Parties").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VE_Parties>("OBLIVIUS_MAINModel.FK_User_Party", "VE_Parties").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VE_Parties> VE_PartiesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VE_Parties>("OBLIVIUS_MAINModel.FK_User_Party", "VE_Parties");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VE_Parties>("OBLIVIUS_MAINModel.FK_User_Party", "VE_Parties", value);
                }
            }
        }

        #endregion
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="OBLIVIUS_MAINModel", Name="GetResults_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetResults_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetResults_Result object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="c2014_WeightedEstimate">Initial value of the C2014_WeightedEstimate property.</param>
        /// <param name="c2014_Estimate">Initial value of the C2014_Estimate property.</param>
        public static GetResults_Result CreateGetResults_Result(global::System.Int32 id, global::System.String name, global::System.Double c2014_WeightedEstimate, global::System.Double c2014_Estimate)
        {
            GetResults_Result getResults_Result = new GetResults_Result();
            getResults_Result.ID = id;
            getResults_Result.Name = name;
            getResults_Result.C2014_WeightedEstimate = c2014_WeightedEstimate;
            getResults_Result.C2014_Estimate = c2014_Estimate;
            return getResults_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalVotes
        {
            get
            {
                return _TotalVotes;
            }
            set
            {
                OnTotalVotesChanging(value);
                ReportPropertyChanging("TotalVotes");
                _TotalVotes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalVotes");
                OnTotalVotesChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalVotes;
        partial void OnTotalVotesChanging(Nullable<global::System.Int32> value);
        partial void OnTotalVotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> TotalWeightedVotes
        {
            get
            {
                return _TotalWeightedVotes;
            }
            set
            {
                OnTotalWeightedVotesChanging(value);
                ReportPropertyChanging("TotalWeightedVotes");
                _TotalWeightedVotes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalWeightedVotes");
                OnTotalWeightedVotesChanged();
            }
        }
        private Nullable<global::System.Double> _TotalWeightedVotes;
        partial void OnTotalWeightedVotesChanging(Nullable<global::System.Double> value);
        partial void OnTotalWeightedVotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Elections2012
        {
            get
            {
                return _Elections2012;
            }
            set
            {
                OnElections2012Changing(value);
                ReportPropertyChanging("Elections2012");
                _Elections2012 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Elections2012");
                OnElections2012Changed();
            }
        }
        private Nullable<global::System.Decimal> _Elections2012;
        partial void OnElections2012Changing(Nullable<global::System.Decimal> value);
        partial void OnElections2012Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> C2012_App
        {
            get
            {
                return _C2012_App;
            }
            set
            {
                OnC2012_AppChanging(value);
                ReportPropertyChanging("C2012_App");
                _C2012_App = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C2012_App");
                OnC2012_AppChanged();
            }
        }
        private Nullable<global::System.Decimal> _C2012_App;
        partial void OnC2012_AppChanging(Nullable<global::System.Decimal> value);
        partial void OnC2012_AppChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> iFactor
        {
            get
            {
                return _iFactor;
            }
            set
            {
                OniFactorChanging(value);
                ReportPropertyChanging("iFactor");
                _iFactor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iFactor");
                OniFactorChanged();
            }
        }
        private Nullable<global::System.Double> _iFactor;
        partial void OniFactorChanging(Nullable<global::System.Double> value);
        partial void OniFactorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Perc
        {
            get
            {
                return _Perc;
            }
            set
            {
                OnPercChanging(value);
                ReportPropertyChanging("Perc");
                _Perc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Perc");
                OnPercChanged();
            }
        }
        private Nullable<global::System.Decimal> _Perc;
        partial void OnPercChanging(Nullable<global::System.Decimal> value);
        partial void OnPercChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> WeightedPerc
        {
            get
            {
                return _WeightedPerc;
            }
            set
            {
                OnWeightedPercChanging(value);
                ReportPropertyChanging("WeightedPerc");
                _WeightedPerc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WeightedPerc");
                OnWeightedPercChanged();
            }
        }
        private Nullable<global::System.Double> _WeightedPerc;
        partial void OnWeightedPercChanging(Nullable<global::System.Double> value);
        partial void OnWeightedPercChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double C2014_WeightedEstimate
        {
            get
            {
                return _C2014_WeightedEstimate;
            }
            set
            {
                OnC2014_WeightedEstimateChanging(value);
                ReportPropertyChanging("C2014_WeightedEstimate");
                _C2014_WeightedEstimate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C2014_WeightedEstimate");
                OnC2014_WeightedEstimateChanged();
            }
        }
        private global::System.Double _C2014_WeightedEstimate;
        partial void OnC2014_WeightedEstimateChanging(global::System.Double value);
        partial void OnC2014_WeightedEstimateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double C2014_Estimate
        {
            get
            {
                return _C2014_Estimate;
            }
            set
            {
                OnC2014_EstimateChanging(value);
                ReportPropertyChanging("C2014_Estimate");
                _C2014_Estimate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C2014_Estimate");
                OnC2014_EstimateChanged();
            }
        }
        private global::System.Double _C2014_Estimate;
        partial void OnC2014_EstimateChanging(global::System.Double value);
        partial void OnC2014_EstimateChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="OBLIVIUS_MAINModel", Name="PartyByAge_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class PartyByAge_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ηλικία
        {
            get
            {
                return _Ηλικία;
            }
            set
            {
                OnΗλικίαChanging(value);
                ReportPropertyChanging("Ηλικία");
                _Ηλικία = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ηλικία");
                OnΗλικίαChanged();
            }
        }
        private global::System.String _Ηλικία;
        partial void OnΗλικίαChanging(global::System.String value);
        partial void OnΗλικίαChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ψήφοι
        {
            get
            {
                return _Ψήφοι;
            }
            set
            {
                OnΨήφοιChanging(value);
                ReportPropertyChanging("Ψήφοι");
                _Ψήφοι = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ψήφοι");
                OnΨήφοιChanged();
            }
        }
        private Nullable<global::System.Int32> _Ψήφοι;
        partial void OnΨήφοιChanging(Nullable<global::System.Int32> value);
        partial void OnΨήφοιChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="OBLIVIUS_MAINModel", Name="PartyByPerif_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class PartyByPerif_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PartyByPerif_Result object.
        /// </summary>
        /// <param name="εκλ_Περιφέρεια">Initial value of the Εκλ_Περιφέρεια property.</param>
        public static PartyByPerif_Result CreatePartyByPerif_Result(global::System.String εκλ_Περιφέρεια)
        {
            PartyByPerif_Result partyByPerif_Result = new PartyByPerif_Result();
            partyByPerif_Result.Εκλ_Περιφέρεια = εκλ_Περιφέρεια;
            return partyByPerif_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Εκλ_Περιφέρεια
        {
            get
            {
                return _Εκλ_Περιφέρεια;
            }
            set
            {
                OnΕκλ_ΠεριφέρειαChanging(value);
                ReportPropertyChanging("Εκλ_Περιφέρεια");
                _Εκλ_Περιφέρεια = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Εκλ_Περιφέρεια");
                OnΕκλ_ΠεριφέρειαChanged();
            }
        }
        private global::System.String _Εκλ_Περιφέρεια;
        partial void OnΕκλ_ΠεριφέρειαChanging(global::System.String value);
        partial void OnΕκλ_ΠεριφέρειαChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ψήφοι
        {
            get
            {
                return _Ψήφοι;
            }
            set
            {
                OnΨήφοιChanging(value);
                ReportPropertyChanging("Ψήφοι");
                _Ψήφοι = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ψήφοι");
                OnΨήφοιChanged();
            }
        }
        private Nullable<global::System.Int32> _Ψήφοι;
        partial void OnΨήφοιChanging(Nullable<global::System.Int32> value);
        partial void OnΨήφοιChanged();

        #endregion
    }

    #endregion
    
}
